"""create_14_entities_and_system_config

Revision ID: 240cf8cf4359
Revises: 
Create Date: 2026-09-24 14:49:08.227304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.base

# revision identifiers, used by Alembic.
revision: str = '240cf8cf4359'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('registration', sa.String(length=16), nullable=False),
    sa.Column('type_code', sa.String(length=8), nullable=False),
    sa.Column('size_class', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='aircraftsizeclass'), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_registration'), 'aircraft', ['registration'], unique=True)
    op.create_table('airports',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_code'), 'airports', ['code'], unique=True)
    op.create_table('audit_records',
    sa.Column('action', sa.Enum('PREDICTION_RUN', 'OPTIMIZATION_RUN', 'SCENARIO_RUN', 'ASSIGNMENT_ACCEPT', 'ASSIGNMENT_REJECT', 'DATA_UPLOAD', name='auditaction'), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('reference_id', app.models.base.GUID(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_action'), 'audit_records', ['action'], unique=False)
    op.create_index('ix_audit_records_action_created', 'audit_records', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_records_reference_id'), 'audit_records', ['reference_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('type', sa.Enum('HEAVY_RAIN', 'RUNWAY_CLOSURE', 'GATE_CLOSURE', 'TRAFFIC_SURGE', 'FLIGHT_DELAY', 'GATE_CONFLICT', 'CASCADE_DELAY', name='scenariotype'), nullable=False),
    sa.Column('target_reference', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resulting_optimization_run_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resulting_optimization_run_id'], ['optimization_runs.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('risk_low_max_minutes', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_medium_max_minutes', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('turnaround_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('optimizer_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('optimizer_weight_delay_cost', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('optimizer_weight_conflict_cost', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('optimizer_weight_reassignment_cost', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('optimizer_weight_taxi_distance', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('optimizer_weight_remote_stand', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('cascade_max_depth', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_runs',
    sa.Column('run_type', sa.Enum('BASELINE', 'MILP', name='runtype'), nullable=False),
    sa.Column('scenario_id', app.models.base.GUID(), nullable=True),
    sa.Column('solver_used', sa.Enum('GUROBI', 'ORTOOLS', 'NONE', name='solverused'), nullable=False),
    sa.Column('solver_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'OPTIMAL', 'FEASIBLE', 'INFEASIBLE', 'TIMEOUT', 'SOLVER_UNAVAILABLE', 'ERROR', name='optimizationstatus'), nullable=False),
    sa.Column('objective_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('solve_time_ms', sa.Integer(), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=True),
    sa.Column('validation_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('config_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opt_runs_status_created', 'optimization_runs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_optimization_runs_scenario_id'), 'optimization_runs', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_optimization_runs_status'), 'optimization_runs', ['status'], unique=False)
    op.create_table('runways',
    sa.Column('airport_id', app.models.base.GUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='runwaystatus'), nullable=False),
    sa.Column('taxi_base_minutes', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airport_id', 'code', name='uq_runways_airport_code')
    )
    op.create_index(op.f('ix_runways_airport_id'), 'runways', ['airport_id'], unique=False)
    op.create_index(op.f('ix_runways_status'), 'runways', ['status'], unique=False)
    op.create_table('terminals',
    sa.Column('airport_id', app.models.base.GUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airport_id', 'code', name='uq_terminals_airport_code')
    )
    op.create_index(op.f('ix_terminals_airport_id'), 'terminals', ['airport_id'], unique=False)
    op.create_table('weather_records',
    sa.Column('airport_id', app.models.base.GUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('condition', sa.Enum('CLEAR', 'RAIN', 'HEAVY_RAIN', 'FOG', 'SNOW', name='weathercondition'), nullable=False),
    sa.Column('wind_speed_kt', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('visibility_m', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_records_airport_id'), 'weather_records', ['airport_id'], unique=False)
    op.create_index('ix_weather_records_airport_time', 'weather_records', ['airport_id', 'recorded_at'], unique=False)
    op.create_table('flights',
    sa.Column('flight_number', sa.String(length=8), nullable=False),
    sa.Column('airline', sa.String(length=4), nullable=False),
    sa.Column('aircraft_id', app.models.base.GUID(), nullable=False),
    sa.Column('route_type', sa.Enum('DOMESTIC', 'INTERNATIONAL', name='routetype'), nullable=False),
    sa.Column('origin', sa.String(length=4), nullable=True),
    sa.Column('destination', sa.String(length=4), nullable=True),
    sa.Column('runway_id', app.models.base.GUID(), nullable=True),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['runway_id'], ['runways.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_number', 'scheduled_arrival', name='uq_flights_flight_arrival')
    )
    op.create_index(op.f('ix_flights_aircraft_id'), 'flights', ['aircraft_id'], unique=False)
    op.create_index('ix_flights_arrival_route', 'flights', ['scheduled_arrival', 'route_type'], unique=False)
    op.create_index(op.f('ix_flights_route_type'), 'flights', ['route_type'], unique=False)
    op.create_index(op.f('ix_flights_runway_id'), 'flights', ['runway_id'], unique=False)
    op.create_index(op.f('ix_flights_scheduled_arrival'), 'flights', ['scheduled_arrival'], unique=False)
    op.create_table('gates',
    sa.Column('terminal_id', app.models.base.GUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('gate_type', sa.Enum('JETBRIDGE', 'REMOTE', name='gatetype'), nullable=False),
    sa.Column('max_aircraft_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='aircraftsizeclass'), nullable=False),
    sa.Column('eligible_route_types', sa.Enum('DOMESTIC', 'INTERNATIONAL', 'BOTH', name='gateeligibleroutetype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'BLOCKED', name='gatestatus'), nullable=False),
    sa.Column('taxi_distance_meters', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_id', 'code', name='uq_gates_terminal_code')
    )
    op.create_index(op.f('ix_gates_gate_type'), 'gates', ['gate_type'], unique=False)
    op.create_index(op.f('ix_gates_status'), 'gates', ['status'], unique=False)
    op.create_index('ix_gates_status_gate_type', 'gates', ['status', 'gate_type'], unique=False)
    op.create_index(op.f('ix_gates_terminal_id'), 'gates', ['terminal_id'], unique=False)
    op.create_table('alerts',
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('category', sa.Enum('CONFLICT', 'HIGH_RISK', 'INFEASIBLE', 'SOLVER_ISSUE', 'CASCADE', name='alertcategory'), nullable=False),
    sa.Column('flight_id', app.models.base.GUID(), nullable=True),
    sa.Column('gate_id', app.models.base.GUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_flight_id'), 'alerts', ['flight_id'], unique=False)
    op.create_index(op.f('ix_alerts_gate_id'), 'alerts', ['gate_id'], unique=False)
    op.create_index(op.f('ix_alerts_resolved'), 'alerts', ['resolved'], unique=False)
    op.create_index('ix_alerts_resolved_severity', 'alerts', ['resolved', 'severity'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('cascade_events',
    sa.Column('root_flight_id', app.models.base.GUID(), nullable=True),
    sa.Column('root_gate_id', app.models.base.GUID(), nullable=True),
    sa.Column('root_runway_id', app.models.base.GUID(), nullable=True),
    sa.Column('scenario_id', app.models.base.GUID(), nullable=True),
    sa.Column('propagation_path', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('affected_flight_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['root_flight_id'], ['flights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['root_gate_id'], ['gates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['root_runway_id'], ['runways.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cascade_events_root_flight_id'), 'cascade_events', ['root_flight_id'], unique=False)
    op.create_index(op.f('ix_cascade_events_root_gate_id'), 'cascade_events', ['root_gate_id'], unique=False)
    op.create_index(op.f('ix_cascade_events_root_runway_id'), 'cascade_events', ['root_runway_id'], unique=False)
    op.create_index(op.f('ix_cascade_events_scenario_id'), 'cascade_events', ['scenario_id'], unique=False)
    op.create_table('gate_assignments',
    sa.Column('optimization_run_id', app.models.base.GUID(), nullable=False),
    sa.Column('flight_id', app.models.base.GUID(), nullable=False),
    sa.Column('gate_id', app.models.base.GUID(), nullable=True),
    sa.Column('assignment_status', sa.Enum('BASELINE', 'PROPOSED', 'COMMITTED', 'REJECTED', name='assignmentstatus'), nullable=False),
    sa.Column('objective_contribution', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('optimization_run_id', 'flight_id', name='uq_gate_assignments_run_flight')
    )
    op.create_index(op.f('ix_gate_assignments_assignment_status'), 'gate_assignments', ['assignment_status'], unique=False)
    op.create_index(op.f('ix_gate_assignments_flight_id'), 'gate_assignments', ['flight_id'], unique=False)
    op.create_index(op.f('ix_gate_assignments_gate_id'), 'gate_assignments', ['gate_id'], unique=False)
    op.create_index('ix_gate_assignments_gate_status', 'gate_assignments', ['gate_id', 'assignment_status'], unique=False)
    op.create_index(op.f('ix_gate_assignments_optimization_run_id'), 'gate_assignments', ['optimization_run_id'], unique=False)
    op.create_table('predictions',
    sa.Column('flight_id', app.models.base.GUID(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('predicted_taxi_minutes', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('predicted_delay_minutes', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('feature_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.models.base.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_flight_id'), 'predictions', ['flight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_flight_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_gate_assignments_optimization_run_id'), table_name='gate_assignments')
    op.drop_index('ix_gate_assignments_gate_status', table_name='gate_assignments')
    op.drop_index(op.f('ix_gate_assignments_gate_id'), table_name='gate_assignments')
    op.drop_index(op.f('ix_gate_assignments_flight_id'), table_name='gate_assignments')
    op.drop_index(op.f('ix_gate_assignments_assignment_status'), table_name='gate_assignments')
    op.drop_table('gate_assignments')
    op.drop_index(op.f('ix_cascade_events_scenario_id'), table_name='cascade_events')
    op.drop_index(op.f('ix_cascade_events_root_runway_id'), table_name='cascade_events')
    op.drop_index(op.f('ix_cascade_events_root_gate_id'), table_name='cascade_events')
    op.drop_index(op.f('ix_cascade_events_root_flight_id'), table_name='cascade_events')
    op.drop_table('cascade_events')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index('ix_alerts_resolved_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_gate_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_flight_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_gates_terminal_id'), table_name='gates')
    op.drop_index('ix_gates_status_gate_type', table_name='gates')
    op.drop_index(op.f('ix_gates_status'), table_name='gates')
    op.drop_index(op.f('ix_gates_gate_type'), table_name='gates')
    op.drop_table('gates')
    op.drop_index(op.f('ix_flights_scheduled_arrival'), table_name='flights')
    op.drop_index(op.f('ix_flights_runway_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_route_type'), table_name='flights')
    op.drop_index('ix_flights_arrival_route', table_name='flights')
    op.drop_index(op.f('ix_flights_aircraft_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_index('ix_weather_records_airport_time', table_name='weather_records')
    op.drop_index(op.f('ix_weather_records_airport_id'), table_name='weather_records')
    op.drop_table('weather_records')
    op.drop_index(op.f('ix_terminals_airport_id'), table_name='terminals')
    op.drop_table('terminals')
    op.drop_index(op.f('ix_runways_status'), table_name='runways')
    op.drop_index(op.f('ix_runways_airport_id'), table_name='runways')
    op.drop_table('runways')
    op.drop_index(op.f('ix_optimization_runs_status'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_scenario_id'), table_name='optimization_runs')
    op.drop_index('ix_opt_runs_status_created', table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_table('system_config')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_audit_records_reference_id'), table_name='audit_records')
    op.drop_index('ix_audit_records_action_created', table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_action'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_airports_code'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_aircraft_registration'), table_name='aircraft')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
